<?php

return [
    'supported' => [
        'USD' => 'US Dollar',
        'EUR' => 'Euro',
        'GBP' => 'British Pound',
        'JPY' => 'Japanese Yen',
        'AUD' => 'Australian Dollar',
        'CAD' => 'Canadian Dollar',
        'CHF' => 'Swiss Franc',
        'CNY' => 'Chinese Yuan',
        'INR' => 'Indian Rupee',
        'MXN' => 'Mexican Peso',
        'BRL' => 'Brazilian Real',
        'ZAR' => 'South African Rand',
        'NZD' => 'New Zealand Dollar',
        'SGD' => 'Singapore Dollar',
        'HKD' => 'Hong Kong Dollar',
        'NOK' => 'Norwegian Krone',
        'SEK' => 'Swedish Krona',
        'DKK' => 'Danish Krone',
        'PLN' => 'Polish Zloty',
        'THB' => 'Thai Baht',
        'IDR' => 'Indonesian Rupiah',
        'MYR' => 'Malaysian Ringgit',
        'PHP' => 'Philippine Peso',
        'KRW' => 'South Korean Won',
        'TRY' => 'Turkish Lira',
        'RUB' => 'Russian Ruble',
        'AED' => 'UAE Dirham',
        'SAR' => 'Saudi Riyal',
        'EGP' => 'Egyptian Pound',
        'NGN' => 'Nigerian Naira',
    ],
];
